apiVersion: apps/v1
kind: Deployment
metadata: 
  name: goclient
spec:
  selector:
    matchLabels:
      app: goclient
  template:
    metadata:
      labels:
        app: goclient
    spec:
      containers:
      - name: goclient
        image: 192.168.1.62:5000/goclient 
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          value: "8081"
        - name: GOSERVERADDR
          value: "goserver:8085"
---
apiVersion: v1
kind: Service
metadata:
  name: goclient
spec: 
  type: NodePort
  selector:
    app: goclient
  ports:
  - name: goclient
    port: 8081
    targetPort: 8081
    nodePort: 30039
          
