apiVersion: apps/v1
kind: Deployment
metadata: 
  name: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
      - name: goserver
        image: 192.168.1.62:5000/goserver 
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          value: "8081"
        - name: GRPCPORT
          value: "8085"
---
apiVersion: v1
kind: Service
metadata:
  name: goserver
spec: 
  type: ClusterIP
  selector:
    app: goserver
  ports:
#  - name: goserver
#    port: 8081
#    targetPort: 8081
#    nodePort: 30036
  - name: grpc
    port: 8085
    targetPort: 8085
          
