apiVersion: apps/v1
kind: Deployment
metadata: 
  name: goserver
spec:
  selector:
    matchLables:
      app: goserver
    template:
      metadata:
        labels:
          app: goserver
      spec:
        containers:
        - name: goserver
          image: 
          port:
          - containerPort: 8081
          env:
          - name: PORT
            value: "8081"
---
apiVersion: v1
kind: Service
metadata:
  name: goserver
spec: 
  type: ClousterIP
  selector:
    app: goserver
  ports:
  - name: goserver
    port: 8081
    targetPort: 8081
          