apiVersion: apps/v1
kind: Deployment
metadata: 
  name: pythonserver
spec:
  selector:
    matchLabels:
      app: pythonserver
  template:
    metadata:
      labels:
        app: pythonserver
    spec:
      containers:
      - name: pythonserver
        image: 192.168.1.62:5000/pythonserver 
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          value: "8081"
---
apiVersion: v1
kind: Service
metadata:
  name: pythonserver
spec: 
  type: NodePort
  selector:
    app: pythonserver
  ports:
  - name: pythonserver
    port: 8081
    targetPort: 8081
    nodePort: 30037